stages:
    - publish-utils

publish-utils:
    stage: publish-utils
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/flux-publish-utils:latest
    script:
        - publish-utils
    only:
        - main
